version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - my-db:/var/lib/mysql  
    command: mysqld --sql_mode=""  
  application:
    container_name: application
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  my-db:
  node_modules: